Repository NVIDIA/thrust, pull requests merged in 2020-07, with the labels that each got.

#1186 Use placeholder expressions
  thrust/system/cuda/detail/find.h
  thrust/system/cuda/detail/remove.h
  thrust/system/cuda/detail/replace.h
  thrust/system/detail/generic/find.inl
  thrust/system/detail/generic/mismatch.inl
  thrust/system/detail/generic/replace.inl
  thrust/system/detail/generic/sequence.inl
Labels: multiconfig: passed, testing: passed

#1207 Legacy Makefiles: Don't force C++14 with GCC 4.8
  Makefile
Labels: nvbug

#1219 Create wrapper to use when including <algorithm> and <memory>
  thrust/addressof.h
  thrust/detail/algorithm_wrapper.h
  thrust/detail/allocator/copy_construct_range.inl
  thrust/detail/allocator/destroy_range.inl
  thrust/detail/allocator/fill_construct_range.inl
  thrust/detail/internal_functional.h
  thrust/detail/memory_algorithms.h
  thrust/detail/memory_wrapper.h
  thrust/detail/temporary_array.h
  thrust/host_vector.h
  thrust/mr/disjoint_pool.h
  thrust/mr/pool.h
  thrust/system/cuda/detail/future.inl
Labels: multiconfig: passed, testing: passed

#1223 Handle deprecated C++17 std::allocator API.
  thrust/detail/allocator/allocator_traits.inl
Labels: multiconfig: passed

#1221 Replace allocator and vector classes with alias templates
  thrust/system/cpp/memory.h
  thrust/system/cpp/vector.h
  thrust/system/cuda/detail/vector.inl
  thrust/system/cuda/memory.h
  thrust/system/cuda/vector.h
  thrust/system/omp/detail/vector.inl
  thrust/system/omp/memory.h
  thrust/system/omp/vector.h
  thrust/system/tbb/detail/vector.inl
  thrust/system/tbb/memory.h
  thrust/system/tbb/vector.h
Labels: multiconfig: passed, testing: in progress

#1201 Add tests for legacy and per-thread default streams
  testing/CMakeLists.txt
  testing/cuda/stream_legacy.cu
  testing/cuda/stream_per_thread.cmake
  testing/cuda/stream_per_thread.cu
  testing/cuda/stream_per_thread.mk
Labels: testing: in progress
