Repository NVIDIA/thrust, pull requests merged in 2020-06, with the labels that each got.

#1158 Fix issues so all host/device combinations build and pass tests.
  CMakeLists.txt
  examples/discrete_voronoi.cu
  testing/copy.cu
  testing/shuffle.cu
  testing/unittest_static_assert.cu
  thrust/cmake/thrust-config.cmake
  thrust/detail/function.h
  thrust/detail/internal_functional.h
  thrust/iterator/detail/zip_iterator_base.h
  thrust/system/tbb/detail/reduce_by_key.inl
  thrust/system/tbb/detail/scan.inl
  thrust/system/tbb/detail/sort.inl
Labels: testing: passed, testing: screened

#966 Fix C4244 from MSVC in sort.
  thrust/system/cuda/detail/sort.h
Labels: testing: passed, testing: screened

#990 cuda/detail/malloc_and_free doesn't include thrust/system/cuda/memory.h
  thrust/system/cuda/detail/malloc_and_free.h
Labels: testing: passed, testing: screened

#1009 Avoid returning uninitialized allocator
  thrust/detail/allocator/allocator_traits.inl
Labels: testing: passed, testing: screened

#1042 Fix return type of predicate_to_integral::operator()
  thrust/detail/internal_functional.h
Labels: testing: passed, testing: screened

#1157 Update .gitignore to exclude my build directories
  .gitignore
Labels: docs only

#1181 Fix compilation for clang cuda compiler
  testing/event.cu
  testing/future.cu
  testing/uninitialized_fill.cu
  testing/unittest/runtime_static_assert.h
Labels: testing: passed, testing: screened

#1184 Enable MultiConfig builds
  CMakeLists.txt
  cmake/ThrustBuildCompilerTargets.cmake
  cmake/ThrustBuildTargetList.cmake
  cmake/ThrustCUDAConfig.cmake
  cmake/ThrustHeaderTesting.cmake
  cmake/ThrustMultiConfig.cmake
  cmake/ThrustRunExample.cmake
  cmake/ThrustRunTest.cmake
  cmake/ThrustUtilities.cmake
  cmake/common_variables.cmake
  cmake/header_test.in
  cmake/run_example.cmake
  cmake/wrap_source_file.cpp.in
  examples/CMakeLists.txt
  examples/cuda/CMakeLists.txt
  testing/CMakeLists.txt
  testing/cpp/CMakeLists.txt
  testing/cuda/CMakeLists.txt
  testing/omp/CMakeLists.txt
  testing/regression/CMakeLists.txt
  testing/unittest/CMakeLists.txt
  thrust/cmake/README.md
  thrust/cmake/thrust-config.cmake
Labels: cmake, multiconfig: passed

#1177 Add transform_input_output_iterator
  examples/transform_input_output_iterator.cu
  internal/test/thrust.example.transform_input_output_iterator.filecheck
  testing/transform_input_output_iterator.cu
  thrust/iterator/detail/transform_input_output_iterator.inl
  thrust/iterator/detail/transform_output_iterator.inl
  thrust/iterator/transform_input_output_iterator.h
  thrust/iterator/transform_output_iterator.h
Labels: multiconfig: passed, testing: in progress
