Repository NVIDIA/thrust, pull requests merged in 2020-09, with the labels that each got.

#1258 Ensure the CUDA radix sort backend synchronizes before returning
  thrust/system/cuda/detail/sort.h
Labels: needed by nvc++

#1281 Update FindTBB.cmake to work with latest MSVC.
  thrust/cmake/FindTBB.cmake
Labels: cmake

#1272 Fix ambiguous overload when using partition with STL containers
  thrust/system/detail/sequential/partition.h
Labels: multiconfig: passed, testing: passed
