Repository NVIDIA/thrust, pull requests merged in 2021-02, with the labels that each got.

#1363 Add option to enable all supported standards in for multiconfig.
  CMakeLists.txt
  ci/common/build.bash
  cmake/DetectSupportedStandards.cmake
  cmake/ThrustBuildTargetList.cmake
  cmake/ThrustFindThrust.cmake
  cmake/ThrustMultiConfig.cmake
Labels: cmake

#1382 Update CMake `Thrust_DIR` documentation.
  thrust/cmake/README.md
Labels: docs only

#1380 Fix typos in `set_operations`
  thrust/set_operations.h
Labels: docs only

#1376 Modernize scan_by_key functors / type deductions.
  testing/scan_by_key.cu
  thrust/system/cuda/detail/scan_by_key.h
  thrust/system/detail/generic/scan_by_key.inl
  thrust/system/detail/sequential/scan_by_key.h
Labels: testing: dvs passed, testing: mc passed

#1384 Add precondition to gather documentation.
  thrust/gather.h
Labels: docs only

#1383 Add FreeBSD License to LICENSE for `complex` implementation.
  LICENSE
  NOTICE
Labels: docs only

#1389 Support building the test suite without CUDA language enabled.
  cmake/ThrustBuildTargetList.cmake
Labels: cmake, needed by nvc++

#1386 Update openmp check.
  thrust/detail/config/compiler.h
Labels: testing: dvs passed, testing: mc passed

#1388 Fix signbit(double) implementation on MSVC.
  thrust/detail/complex/c99math.h
Labels: functional bug, testing: dvs passed, testing: mc passed
