Repository NVIDIA/thrust, pull requests merged in 2021-07, with the labels that each got.

#1457 Fix tuple_size/tuple_element for cv-qualified types
  testing/pair.cu
  thrust/detail/pair.inl
  thrust/detail/tuple.inl
  thrust/tuple.h
Labels: testing: gpuCI passed, testing: internal ci passed

#1488 Fix path to installed cub in thrust-config.cmake [NVBug 3340746]
  thrust/cmake/thrust-config.cmake
Labels: P0: must have, bug: functional, nvbug, only: cmake, only: tests, testing: gpuCI passed

#1491 thrust::iterator_traits to inherit from std::iterator_traits
  thrust/iterator/iterator_traits.h
Labels: P1: should have, enhancement, helps: rapids, testing: gpuCI in progress, testing: internal ci in progress

#1471 Reduce scan_by_key memory consumption
  thrust/system/detail/generic/scan_by_key.inl
Labels: P1: should have, bug: performance, testing: gpuCI in progress, testing: internal ci in progress

#1492 Pull the fully qualified cub:: namespace into thrust::
  thrust/system/cuda/config.h
  thrust/system/cuda/detail/adjacent_difference.h
  thrust/system/cuda/detail/async/exclusive_scan.h
  thrust/system/cuda/detail/async/inclusive_scan.h
  thrust/system/cuda/detail/async/reduce.h
  thrust/system/cuda/detail/async/sort.h
  thrust/system/cuda/detail/binary_search.h
  thrust/system/cuda/detail/copy_if.h
  thrust/system/cuda/detail/core/agent_launcher.h
  thrust/system/cuda/detail/core/util.h
  thrust/system/cuda/detail/extrema.h
  thrust/system/cuda/detail/malloc_and_free.h
  thrust/system/cuda/detail/merge.h
  thrust/system/cuda/detail/partition.h
  thrust/system/cuda/detail/reduce.h
  thrust/system/cuda/detail/reduce_by_key.h
  thrust/system/cuda/detail/scan.h
  thrust/system/cuda/detail/scan_by_key.h
  thrust/system/cuda/detail/set_operations.h
  thrust/system/cuda/detail/sort.h
  thrust/system/cuda/detail/unique.h
  thrust/system/cuda/detail/unique_by_key.h
Labels: P1: should have, enhancement, testing: gpuCI passed, testing: internal ci passed
