Repository NVIDIA/thrust, pull requests merged in 2021-09, with the labels that each got.

#1518 Fix std::allocator traits
  thrust/detail/allocator/allocator_traits.h
Labels: P0: must have

#1514 Fix default constructor of counting iterator
  testing/counting_iterator.cu
  thrust/iterator/counting_iterator.h
Labels: testing: gpuCI passed, testing: internal ci in progress

#1509 Fixed call of max() on MSVC compiler
  thrust/mr/allocator.h
Labels: testing: gpuCI passed, testing: internal ci passed
