Repository NVIDIA/thrust, pull requests merged in 2021-05, with the labels that each got.

#1430 [NVBug 3308316] Update deprecation messages for CTK 11.4.
  thrust/detail/config/cpp_dialect.h
Labels: P0: must have, nvbug

#1438 Update Changelog for 1.12.1.
  CHANGELOG.md
  README.md
Labels: only: docs

#1435 [gpuCI] Clear stale CMake files and report failures.
  ci/common/build.bash
Labels: only: gpuci

#1431 Document that the patch number is no longer used.
  CONTRIBUTING.md
  thrust/version.h
Labels: only: docs

#1432 Update Thrust's build instructions for NVIDIA/cub#298.
  CONTRIBUTING.md
Labels: helps: pytorch, only: docs

#1423 Fix transform_iterator with non-copyable types
  testing/transform_iterator.cu
  thrust/iterator/transform_iterator.h
Labels: testing: internal ci passed, testing: mc passed

#1440 Suppress scan failures in icc gpuCI.
  ci/common/build.bash
Labels: only: gpuci, testing: mc in progress
