Repository NVIDIA/thrust, pull requests merged in 2022-05, with the labels that each got.

#1631 Add GDB pretty-printer for thrust vectors and references
  scripts/gdb-pretty-printers.py
Labels: type: enhancement, P2: nice to have

#1647 Add __forceinline__ to thrust::detail::wrapped_function::operator()
  thrust/detail/function.h
Labels: type: enhancement, P2: nice to have

#1555 Use CUB's ScanByKey implementation
  testing/is_contiguous_iterator.cu
  testing/scan_by_key.cu
  testing/scan_by_key.exclusive.cu
  testing/scan_by_key.inclusive.cu
  thrust/system/cuda/detail/dispatch.h
  thrust/system/cuda/detail/scan_by_key.h
  thrust/type_traits/is_contiguous_iterator.h
Labels: type: enhancement, P2: nice to have, testing: gpuCI in progress

#1669 Add an example that shows how to use custom CUDA streams.
  examples/cuda/explicit_cuda_stream.cu
  internal/test/thrust.example.cuda.explicit_cuda_stream.filecheck
Labels: type: enhancement, P2: nice to have, testing: gpuCI in progress

#1619 Add unique_count algorithm
  testing/cuda/unique.cu
  testing/unique.cu
  thrust/count.h
  thrust/detail/count.h
  thrust/detail/unique.inl
  thrust/system/cuda/detail/unique.h
  thrust/system/detail/generic/unique.h
  thrust/system/detail/generic/unique.inl
  thrust/system/detail/sequential/unique.h
  thrust/system/omp/detail/unique.h
  thrust/system/omp/detail/unique.inl
  thrust/system/tbb/detail/unique.h
  thrust/system/tbb/detail/unique.inl
  thrust/unique.h
Labels: type: enhancement, P2: nice to have

#1512 Use CUB version of CUB adjacent difference
  testing/cuda/adjacent_difference.cu
  thrust/system/cuda/detail/adjacent_difference.h
Labels: type: enhancement, P2: nice to have, backend: CUDA

#1683 Fix bug in final `eval_if` branch in iterator_category_to_traversal.h metafunctions
  thrust/iterator/detail/iterator_category_to_traversal.h
Labels: type: bug: functional, P1: should have, area: iterators

#1687 Make any_system_tag only convertible to other system tags
  thrust/detail/execution_policy.h
  thrust/iterator/detail/any_system_tag.h
  thrust/iterator/detail/device_system_tag.h
  thrust/iterator/detail/host_system_tag.h
Labels: P2: nice to have, type: cleanup, area: iterators

#1694 Revert "Make any_system_tag only convertible to other system tags (#1687)"
  thrust/detail/execution_policy.h
  thrust/iterator/detail/any_system_tag.h
  thrust/iterator/detail/device_system_tag.h
  thrust/iterator/detail/host_system_tag.h
Labels: type: bug: functional, P0: must have, compiler: nvcc, area: iterators
